/*******************************************************************************
 * Eagle3D - generates 3d images from Eagle PCB board files.
 *
 * See the README file for copyright information and how to reach the author.
 ******************************************************************************/

#include "SWITCH/SMT/LSH-series.inc"
#include "SWITCH/THT/SECME.inc"
#include "SWITCH/THT/ITT.inc"
#include "SWITCH/THT/push-button-6x6mm.inc"
#include "SWITCH/THT/rotary-dip-switch.inc"
