/*******************************************************************************
 * Eagle3D - generates 3d images from Eagle PCB board files.
 *
 * See the README file for copyright information and how to reach the author.
 ******************************************************************************/

// the top folder is always TOOLS:
#include "TOOLS/folder.inc"


// after that, no dependencies are expected.
// add alphabetically.
#include "BOARDS/folder.inc"
#include "BUZZER/folder.inc"
#include "CONNECTOR/folder.inc"
#include "CRYSTAL/folder.inc"
#include "DCDC/folder.inc"
#include "DIODE/folder.inc"
#include "FILTER/folder.inc"
#include "FUSE/folder.inc"
#include "HEATSINK/folder.inc"
#include "IC/folder.inc"
#include "INDUCTOR/folder.inc"
#include "OPTO/folder.inc"
#include "RELAY/folder.inc"
#include "SOCKET/folder.inc"
#include "TRANSISTOR/folder.inc"


// deprecated includes
#include "e3d_cap.inc"
#include "e3d_connector.inc"
#include "e3d_diode.inc"
#include "e3d_logo.inc"
#include "e3d_qfp.inc"
#include "e3d_resistor.inc"
#include "e3d_switch.inc"
#include "e3d_tex.inc"
#include "e3d_tools.inc"
#include "e3d_trafo.inc"
#include "e3d_user.inc"
