/*******************************************************************************
 * Eagle3D - generates 3d images from Eagle PCB board files.
 *
 * See the README file for copyright information and how to reach the author.
 ******************************************************************************/


/*******************************************************************************
 * Many dimensions are given in older datasheets in imperial units.
 * However, in Eagle3D all diemension are mm.
 * Define these units as a multiplier.
 ******************************************************************************/
#declare inch = 25.40;
#declare mil = 0.0254;
