/*******************************************************************************
 * Eagle3D - generates 3d images from Eagle PCB board files.
 *
 * See the README file for copyright information and how to reach the author.
 ******************************************************************************/

#include "INDUCTOR/CTC-coils.inc"
#include "INDUCTOR/L_5MM_S.inc"
#include "INDUCTOR/L_EF_core.inc"
#include "INDUCTOR/Murata.inc"
#include "INDUCTOR/Tyco.inc"
#include "INDUCTOR/WuerthElektronik.inc"
#include "INDUCTOR/toroids.inc"
